faup.h:67:14: error: use of enum ‘_faup_last_slash_t’ without previous declaration
    /usr/local/include/faup/faup.h:67:14: error: use of enum ‘_faup_last_slash_t’ without previous declaration
     typedef enum _faup_last_slash_t faup_last_slash_t;
              ^
    /usr/local/include/faup/faup.h:67:50: error: invalid type in declaration before ‘;’ token
 typedef enum _faup_last_slash_t faup_last_slash_t;

I'm guessing it's because of compiler options (g++ c++11).

Writing the typedef after the declaration should work in all compilers.